# Project Euler Problem 2: Even Fibonacci sum
# Each new term in the Fibonacci sequence is
# generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci
# sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fib(n)
  array =[0,1]
  (2..n).map do |num|
    array.push((array[num-2] + array[num-1]))
  end
  array[n]
end


p (1..50).map {|i| fib(i)}.select{|num| num.even? && num < 4_000_000}.reduce(&:+)
# answer is 4613732
